pre: git clone https://github.com/minrk/ligo-binder.git ligo

packages:
    - name      : ipython
      vcs       : conda
      cmd       : mamba install -y
      conda     : mamba
      hierarchy : minor
      supply    : major

    - name      : matplotlib
      vcs       : conda
      cmd       : mamba install -y
      conda     : mamba
      hierarchy : patch
      supply    : minor
      version   : 3.5.2

    - name      : scipy
      vcs       : conda
      conda     : mamba
      cmd       : mamba install -y
      hierarchy : patch
      supply    : minor
      version   : 1.8.0

    - name      : numpy
      vcs       : conda
      cmd       : mamba install -y
      conda     : mamba
      hierarchy : patch
      supply    : minor
      version   : 1.16.0

    - name      : h5py
      vcs       : conda
      cmd       : mamba install -y
      conda     : mamba
      hierarchy : patch
      supply    : minor

    - name      : python
      vcs       : conda
      cmd       : mamba install -y
      conda     : mamba
      hierarchy : patch
      supply    : minor
      version   : 3.7.0


run:
    - cd ligo; python LOSC_Event_tutorial.py; cd ..

post: conda env export > environment.yml
